; PlatformIO Project Configuration File
; Fox Hunter - Beacon firmware
; Hardware: Seeed XIAO nRF52840 + SX1262 LoRa module

[platformio]
boards_dir = ../boards

[env:foxhunter_beacon]
platform = nordicnrf52
platform_packages =
  framework-arduinoadafruitnrf52 @ 1.10700.0
board = seeed-xiao-afruitnrf52-nrf52840
board_build.ldscript = ../boards/nrf52840_s140_v7.ld
board_build.variants_dir = variants
framework = arduino
monitor_speed = 115200
upload_protocol = nrfutil
extra_scripts = post:create-uf2.py

lib_deps =
  SPI
  Wire
  jgromes/RadioLib @ ^7.3.0

build_flags =
  -DRADIOLIB_STATIC_ONLY=1
  -DRADIOLIB_GODMODE=1
  -DRADIOLIB_EXCLUDE_CC1101=1
  -DRADIOLIB_EXCLUDE_RF69=1
  -DRADIOLIB_EXCLUDE_SX1231=1
  -DRADIOLIB_EXCLUDE_SI443X=1
  -DRADIOLIB_EXCLUDE_RFM2X=1
  -DRADIOLIB_EXCLUDE_SX128X=1
  -DRADIOLIB_EXCLUDE_AFSK=1
  -DRADIOLIB_EXCLUDE_AX25=1
  -DRADIOLIB_EXCLUDE_HELLSCHREIBER=1
  -DRADIOLIB_EXCLUDE_MORSE=1
  -DRADIOLIB_EXCLUDE_APRS=1
  -DRADIOLIB_EXCLUDE_BELL=1
  -DRADIOLIB_EXCLUDE_RTTY=1
  -DRADIOLIB_EXCLUDE_SSTV=1
